sudo: required
language: python
env:
  - TEST="Nothing" TEST2="Nothing2"
python:
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
    include:
    - python: 3.7
      dist: xenial
      sudo: true
# services: 
  # - docker
before_install:
  - sudo apt-get -qq update
install:
  # - pip install nose
# command to run tests
script:
  - python ./run.py

after_success:
  - echo 'done'
