jobs:
  include:
    - stage: "Prepare Dependencies"               
      name: "MySQL"           
      script: 
        - sleep 10
        - ifconfig
    - script: 
      - sleep 15
      - ifconfig
      name: "Minio"     
    - stage: "Tests"
      name: "Python 3.7"
      script:
        - sleep 13
        - ifconfig