addons:
  hosts:
    - main
sudo: required
services:
  - docker
jobs:
  include:
    - stage: "Prepare Dependencies"               
      name: "MySQL"           
      script: 
        - ifconfig
        - env
        - docker pull mysql:5.7
        - docker run -d -p 9800:3306 -e MYSQL_ROOT_PASSWORD=simple mysql:5.7
    - script: 
      - ifconfig
      - env
      - docker pull minio/minio
      - docker run -d -p 9000:9000 -e "MINIO_ACCESS_KEY=datajoint" -e "MINIO_SECRET_KEY=datajoint" minio/minio:RELEASE.2019-05-02T19-07-09Z server /data
      name: "Minio"     
    - stage: "Tests"
      name: "Python 3.7"
      script:
        - ifconfig
        - env
        - docker pull minio/mc:RELEASE.2019-05-01T23-27-44Z
        - docker run --network="host" --entrypoint=/bin/sh minio/mc:RELEASE.2019-05-01T23-27-44Z -c "mc config host add dj-s3 http://127.0.0.1:9000 datajoint datajoint;mc mb datajoint-test;mc policy download datajoint-test;exit 0;"