sudo: required
services: 
- docker
matrix:
  include:
  - name: "Push WIN Docker Image"
    os: windows
    language: shell
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    # - docker build -t raphaelguzman/mysql:5.7-nano1803 -f win-mysql.dockerfile .
    # - docker push raphaelguzman/mysql:5.7-nano1803

    # - docker build -t raphaelguzman/minio:2019-05-14-Nano1803 -f win-minio.dockerfile .
    # - docker push raphaelguzman/minio:2019-05-14-Nano1803

    - docker build -t raphaelguzman/minio-mc:2019-05-01-Nano1803 -f win-minio-mc.dockerfile .
    - docker push raphaelguzman/minio-mc:2019-05-01-Nano1803

    # - docker build -t raphaelguzman/datajoint:local-py3.6-nano1803 -f win-dj.dockerfile .
    # - docker push raphaelguzman/minio-mc:local-py3.6-nano1803