# sudo: required
# language: python
# env:
#   - TEST="Nothing" TEST2="Nothing2"
# python:
#   - "3.4"
#   - "3.5"
#   - "3.6"
# matrix:
#     include:
#     - python: 3.7
#       dist: xenial
#       sudo: true
# # services: 
#   # - docker
# before_install:
#   - sudo apt-get -qq update
# install:
#   # - pip install nose
# # command to run tests
# script:
#   - python ./run.py

# Discussed at https://travis-ci.community/t/python-support-on-windows/241/18
language: python            # this works for Linux but is an error on macOS or Windows
env:
  - TEST="Nothing" TEST2="Nothing2"
matrix:
  include:
    - name: "Python 3.7.1 on Xenial Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.7
      after_success: sudo whoami && python --version
    - name: "Python 3.7.2 on macOS"
      os: osx
      osx_image: xcode9.3  # Python 3.7.2 running on macOS 10.14.3 xcode10.2, xcode9.4, 
      language: shell       # 'language: python' is an error on Travis CI macOS
      # python: 3.7         # 'python:' is ignored on Travis CI macOS
      after_success: sudo whoami && brew insall pyenv && python3 --version
    - name: "Python 3.7.3 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      # python: 3.7         # 'python:' is ignored on Travis CI Windows
      before_install: whoami && choco install python --version 3.4.4 && python --version  # this install takes at least 1 min 30 sec 3.7.2, 3.6.7, 3.5.1, 3.4.4
      env: PATH=/c/Python34:/c/Python34/Scripts:$PATH
install: 
  - pip3 install --user --upgrade pip || pip3 install --upgrade pip  # all three OSes agree about 'pip3'
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
script: 
  - python3 run.py || python run.py
