# sudo: required
# language: python
# env:
#   - TEST="Nothing" TEST2="Nothing2"
# python:
#   - "3.4"
#   - "3.5"
#   - "3.6"
# matrix:
#     include:
#     - python: 3.7
#       dist: xenial
#       sudo: true
# # services: 
#   # - docker
# before_install:
#   - sudo apt-get -qq update
# install:
#   # - pip install nose
# # command to run tests
# script:
#   - python ./run.py

# Discussed at https://travis-ci.community/t/python-support-on-windows/241/18
dist: xenial
language: python            # this works for Linux but is an error on macOS or Windows
# python:
# - 3.4
# - 3.5
# - 3.6
# - 3.7
env:
  - TEST="Nothing" TEST2="Nothing2"
matrix:
  include:
    # - name: "Python 3.4 on macOS"
    #   os: osx
    #   osx_image: xcode9.3  # Python 3.7.2 running on macOS 10.14.3 xcode10.2, xcode9.4, 
    #   language: shell       # 'language: python' is an error on Travis CI macOS
    #   cache:
    #     directories:
    #       - $HOME/Library/Caches/Homebrew
    #   before_cache:
    #     - brew cleanup
    #   before_install: 
    #     - brew install zlib
    #     - brew upgrade pyenv
    #     - brew install docker
    #     - pyenv install 3.4.4 
    #     - pyenv global 3.4.4
    #   env: PATH=~/.pyenv/versions/3.4.4/bin:$PATH LDFLAGS=-L/usr/local/opt/zlib/lib CPPFLAGS=-I/usr/local/opt/zlib/include PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig KEEP_BUILD_PATH=true
    - name: "Python 3.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: 
        # - echo dockerd> .\script.ps1
        # - echo $HOME
        # - CACLS $HOME
        # - echo dockerd > $HOME/script.ps1
        # - cat $HOME/script.ps1
        # - powershell -help
        - powershell -command "restart-service *docker*"
        # - powershell -command "dockerd --experimental" &
        # - powershell -file $HOME/script.ps1 &
        # - powershell -command ".\script.ps1"
        # - start-psjob "dockerd --experimental"
        # - START /B dockerd --experimental
        # - dockerd --experimental
        - choco install python --version 3.4.4 # this install takes at least 1 min 30 sec 3.7.2, 3.6.7, 3.5.1, 3.4.4
      env: 
        - PATH=/c/Python34:/c/Python34/Scripts:$PATH
sudo: required
services: 
  - docker
install: 
  # - pip install --user --upgrade pip || pip install --upgrade pip # all three OSes agree about 'pip3'
  - docker images
  - docker pull mcr.microsoft.com/windows/nanoserver:1803
  - docker images
  - docker run microsoft/nanoserver:1803 dir

  # - docker pull vitaliylebedev/nano-minio:latest
  # - docker tag vitaliylebedev/nano-minio:latest minio:v1.0
  # - docker run -d -p 9000:9000 -e "MINIO_ACCESS_KEY=datajoint" -e "MINIO_SECRET_KEY=datajoint" minio:v1.0 C:\tools\minio.exe server C:\Data
  - docker ps
  - python -m pip install --upgrade pip # all three OSes agree about 'pip3'
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
# before_script:
#   - sudo systemctl stop docker
#   - sudo dockerd --experimental &
#   - docker pull --platform linux alpine
#   - docker run -d alpine sleep 10 
#   - docker ps
script: 
  - python run.py
after_success:
  - whoami
  # - python3 --version || python --version
  - python --version
  - pip --version
  - kill $(jobs -p)
