# sudo: required
# language: python
# env:
#   - TEST="Nothing" TEST2="Nothing2"
# python:
#   - "3.4"
#   - "3.5"
#   - "3.6"
# matrix:
#     include:
#     - python: 3.7
#       dist: xenial
#       sudo: true
# # services: 
#   # - docker
# before_install:
#   - sudo apt-get -qq update
# install:
#   # - pip install nose
# # command to run tests
# script:
#   - python ./run.py

# Discussed at https://travis-ci.community/t/python-support-on-windows/241/18
dist: xenial
language: python            # this works for Linux but is an error on macOS or Windows
python:
- 3.4
- 3.5
- 3.6
- 3.7
env:
  - TEST="Nothing" TEST2="Nothing2"
matrix:
  include:
    - name: "Python 3.4 on macOS"
      os: osx
      osx_image: xcode9.3  # Python 3.7.2 running on macOS 10.14.3 xcode10.2, xcode9.4, 
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install: 
        - brew install zlib
        - brew upgrade pyenv
        - pyenv install 3.4.4 
        - pyenv local 3.4.4
      env: PATH=~/.pyenv/versions/2.7.10/bin:$PATH LDFLAGS=-L/usr/local/opt/zlib/lib CPPFLAGS=-I/usr/local/opt/zlib/include PKG_CONFIG_PATH=/usr/local/opt/zlib/lib/pkgconfig KEEP_BUILD_PATH=true
    - name: "Python 3.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install: 
        # - powershell -command "dockerd --experimental"
        - choco install python --version 3.4.4 # this install takes at least 1 min 30 sec 3.7.2, 3.6.7, 3.5.1, 3.4.4
      env: 
        - PATH=/c/Python34:/c/Python34/Scripts:$PATH
services: 
  - docker
install: 
  - pip3 install --user --upgrade pip || pip3 install --upgrade pip  || pip install --upgrade pip # all three OSes agree about 'pip3'
# 'python' points to Python 2.7 on macOS but points to Python 3.7 on Linux and Windows
# 'python3' is a 'command not found' error on Windows but 'py' works on Windows only
before_script:
  - sudo systemctl stop docker
  - sudo dockerd --experimental &
  - docker pull --platform linux alpine
  - docker run -d alpine sleep 10 
  - docker ps
script: 
  - python3 run.py || python run.py
after_success:
  - whoami
  - python3 --version || python --version