sudo: required
services: 
- docker
matrix:
  include:
  - name: "Push WIN Docker Image"
    os: windows
    language: shell
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t raphaelguzman/mysql:5.7-nano1803 -f win-mysql.dockerfile .