version: '3.4'
services:
  # minio:
  #   build:
  #     context: .
  #     dockerfile: win-minio.dockerfile
  #   image: minio:v1.0
  #   # ports:
  #   #   - "9000:9000"
  #   networks:
  #     - main

  mysqlref:
    build:
      context: .
      dockerfile: win-mysql.dockerfile
    image: mysql:v1.0
    # ports:
    #   - "3306:3306"
    networks:
      - main

  # minio-mc:
  #   build:
  #     context: .
  #     dockerfile: win-minio-mc.dockerfile
  #   image: minio_mc:v1.0
  #   depends_on:
  #     - minio
  #   networks:
  #     - main

  # mysql-client:
  #   build:
  #     context: .
  #     dockerfile: win-mysql-client.dockerfile
  #   image: mysql_client:v1.0
  #   depends_on:
  #     - mysqlref
  #   networks:
  #     - main

  datajoint:
    build:
      context: .
      dockerfile: win-dj.dockerfile
    image: dj:v1.0
    depends_on:
      # - minio-mc
      - mysqlref
    environment:
      - DJ_HOST=mysqlref
      - DJ_USER=root
      - DJ_PASS=simple
      - DJ_TEST_HOST=mysqlref
      - DJ_TEST_USER=datajoint
      - DJ_TEST_PASS=datajoint
    networks:
      - main
    command: python run.py
    # user: Administrator

networks:
  main:
    ipam:
      config:
        - subnet: "172.168.1.5/24"
